# Generated by Django 5.0.2 on 2024-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('tamanho', models.CharField(choices=[('P', 'pequeno'), ('M', 'medio'), ('G', 'grande')], max_length=1)),
                ('localidade', models.CharField(max_length=20)),
                ('caracteristica', models.CharField(max_length=20)),
                ('tempo', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('tamanho', models.CharField(choices=[('P', 'pequeno'), ('M', 'medio'), ('G', 'grande')], max_length=1)),
                ('localidade', models.CharField(max_length=20)),
                ('caracteristica', models.CharField(max_length=20)),
                ('tempo', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
    ]
