# Generated by Django 5.0.2 on 2024-03-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_encontrado_cor_alter_encontrado_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontrado',
            name='img',
            field=models.ImageField(default=0, upload_to='uploads/animais'),
        ),
        migrations.AddField(
            model_name='perdido',
            name='img',
            field=models.ImageField(default=0, upload_to='uploads/animais'),
        ),
    ]
