# Generated by Django 5.0.2 on 2024-03-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_encontrado_img_perdido_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrado',
            name='img',
            field=models.ImageField(upload_to='uploads/animais'),
        ),
        migrations.AlterField(
            model_name='perdido',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
    ]
