# Generated by Django 5.0.2 on 2024-03-09 20:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_encontrado_img_alter_perdido_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdido',
            name='caracteristica',
        ),
        migrations.AddField(
            model_name='perdido',
            name='adicional',
            field=models.CharField(max_length=300, null=True, verbose_name='Informações adicionais'),
        ),
        migrations.AddField(
            model_name='perdido',
            name='fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encontrado',
            name='img',
            field=models.ImageField(upload_to='animais/'),
        ),
        migrations.AlterField(
            model_name='perdido',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'cachorro'), ('Cavalo', 'cavalo'), ('Gato', 'gato'), ('Periquito', 'periquito')], max_length=20, verbose_name='Espécie do animal encontrado'),
        ),
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 23, 51, 251261, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data animal perdido'),
        ),
    ]
