# Generated by Django 5.0.2 on 2024-03-09 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_perdido_caracteristica_perdido_adicional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdido',
            name='fk',
        ),
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 25, 42, 134431, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data animal perdido'),
        ),
    ]
