# Generated by Django 5.0.2 on 2024-03-09 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_perdido_fk_alter_perdido_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdido',
            name='adicional',
        ),
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 26, 48, 502322, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data animal perdido'),
        ),
    ]
