# Generated by Django 5.0.2 on 2024-03-09 20:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_perdido_tempo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perdido',
            name='adicional',
            field=models.CharField(max_length=300, null=True, verbose_name='Informações adicionais'),
        ),
        migrations.AddField(
            model_name='perdido',
            name='fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perdido',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 36, 5, 16628, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data animal perdido'),
        ),
    ]
