# Generated by Django 5.0.2 on 2024-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_perdido_especie_alter_perdido_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(),
        ),
    ]
