# Generated by Django 5.0.2 on 2024-03-09 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_perdido_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 22, 19, 40, 157043, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
