# Generated by Django 5.0.2 on 2024-03-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_perdido_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='tempo',
            field=models.DateField(),
        ),
    ]
