# Generated by Django 5.0.2 on 2024-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_perdido_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdido',
            name='fk',
        ),
    ]
