# Generated by Django 5.0.2 on 2024-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_perdido_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdido',
            name='nome',
            field=models.CharField(default='Pet', max_length=20, verbose_name='Nome do animal'),
        ),
    ]
