# Generated by Django 5.0.2 on 2024-03-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_perdido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
