# Generated by Django 5.0.2 on 2024-03-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_rename_encontrado_especie_encontrado_especie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdido',
            old_name='fk',
            new_name='usuario',
        ),
    ]
