# Generated by Django 5.0.2 on 2024-04-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_perdido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/animais/'),
        ),
    ]
