# Generated by Django 5.0.2 on 2024-05-10 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_delete_encontrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='animaisregistrados',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.especie'),
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=20)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.especie')),
            ],
        ),
        migrations.AlterField(
            model_name='animaisregistrados',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.raca'),
        ),
    ]
