# Generated by Django 5.0.2 on 2024-05-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_alter_animaisregistrados_especie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raca',
        ),
    ]
