# Generated by Django 5.0.2 on 2024-05-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_delete_raca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especie',
        ),
    ]
