# Generated by Django 5.0.2 on 2024-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cpf',
            new_name='primeiroNome',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimoNome',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
